title: Cameron Makin
email: prod@sunkenlane.net
instagram_username: cameron.makin
baseurl: ""
url: "http://cameronmakin.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
  fragments:
    output: true
  references:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
