title: Cameron Makin
email: cameronmakin123@gmail.com
instagram_username: cameron.makin
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cameronmakin.com" # the base hostname & protocol for your site, e.g. http://example.co
landingpage: "/projects"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
  fragments:
    output: true
  references:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
